import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}

        <Toaster
          position="top-center"
          gutter={12}
          containerStyle={{
            margin: "8px",
          }}
          toastOptions={{
            // Base styles for all toasts
            style: {
              borderRadius: "12px",
              background: "#1F2937",
              color: "#F9FAFB",
              boxShadow: "0 4px 12px rgba(0, 0, 0, 0.15)",
              padding: "16px 24px",
              fontSize: "14px",
              lineHeight: "1.5",
              maxWidth: "500px",
            },
            duration: 4000,

            // Success variant
            success: {
              duration: 5000,
              iconTheme: {
                primary: "#b266ef", // Emerald-500
                secondary: "#FFFFFF",
              },
              style: {
                background: "#b266ef", // Emerald-900
                borderLeft: "4px solid #10B981",
              },
            },

            // Error variant
            error: {
              iconTheme: {
                primary: "#EF4444", // Red-500
                secondary: "#FFFFFF",
              },
              style: {
                background: "#7F1D1D", // Red-900
                borderLeft: "4px solid #EF4444",
              },
            },

            // Loading variant
            loading: {
              style: {
                background: "#1E40AF", // Blue-800
                borderLeft: "4px solid #3B82F6", // Blue-500
              },
            },

            // Custom variant (trigger with toast.custom())
            custom: {
              style: {
                background: "#6B21A8", // Purple-900
                borderLeft: "4px solid #A855F7", // Purple-500
              },
            },
          }}
        />
      </body>
    </html>
  );
}
